"""Seed generation.

`04`'s acceptance criteria are the first four sections. The golden files under
`tests/fixtures/seeds/` are the format's pin: they are regenerated by writing the
fixture export with `SeedGenerator` and reviewed as a diff, never edited by hand
to make a test pass — a change to them is a change to what a destination chat
receives.
"""

import hashlib
from pathlib import Path

import pytest
from typer.testing import CliRunner

from dataporter import cli, render
from dataporter import seed as seeding
from dataporter.config import AttachmentSettings, SeedSettings, Settings
from dataporter.exit_codes import ExitCode
from dataporter.export import load_export
from dataporter.export.model import Conversation

GOLDEN = Path(__file__).parent / "fixtures" / "seeds"

SIMPLE = "aa000001-1111-4111-8111-111111111111"
LONG = "bb000002-2222-4222-8222-222222222222"
ARTIFACT = "cc000003-3333-4333-8333-333333333333"
ATTACHMENT = "dd000004-4444-4444-8444-444444444444"
BRANCH = "ee000005-5555-4555-8555-555555555555"
EMPTY = "ff000006-6666-4666-8666-666666666666"

MIGRATABLE = [SIMPLE, LONG, ARTIFACT, ATTACHMENT, BRANCH]

OFF_PATH_TEXT = "`ferry` — short, and it carries things across."
"""The branch fixture's abandoned reply. It is never in a seed."""


def one_turn(
    text: str, uuid: str = "aaaaaaaa-1111-4111-8111-111111111111"
) -> Conversation:
    """A one-message conversation, for the rules the fixture does not exercise."""
    return Conversation.model_validate(
        {
            "uuid": uuid,
            "name": "One long turn",
            "created_at": "2024-05-01T09:00:00Z",
            "updated_at": "2024-05-01T09:00:00Z",
            "chat_messages": [
                {
                    "uuid": "m1",
                    "sender": "human",
                    "text": text,
                    "content": [],
                    "created_at": "2024-05-01T09:00:00Z",
                    "updated_at": "2024-05-01T09:00:00Z",
                }
            ],
            "current_leaf_message_uuid": "m1",
        }
    )


def settings_for(attachments_dir: Path, max_chars: int = 50_000) -> Settings:
    return Settings(
        workspace=attachments_dir.parent,
        seed=SeedSettings(max_chars=max_chars),
        attachments=AttachmentSettings(dir=attachments_dir),
    )


def seeds_of(
    export_dir: Path, attachments_dir: Path, max_chars: int = 50_000
) -> dict[str, seeding.SeedOutcome]:
    generator = seeding.SeedGenerator(settings_for(attachments_dir, max_chars))
    export = load_export(export_dir)
    return {
        outcome.conversation_uuid: outcome
        for outcome in generator.seeds(export.conversations)
    }


def seed_of(
    export_dir: Path, attachments_dir: Path, uuid: str, max_chars: int = 50_000
) -> seeding.Seed:
    outcome = seeds_of(export_dir, attachments_dir, max_chars)[uuid]
    assert outcome.seed is not None
    return outcome.seed


# --------------------------------------------------------------------------- #
# Acceptance: the golden files
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("uuid", MIGRATABLE, ids=lambda uuid: uuid[:8])
def test_each_fixture_conversation_matches_its_golden_part(
    export_dir: Path, attachments_dir: Path, uuid: str
) -> None:
    seed = seed_of(export_dir, attachments_dir, uuid)
    expected = (GOLDEN / "default" / uuid / "part-01.txt").read_bytes()
    assert len(seed.chunks) == 1
    assert seed.chunks[0].text.encode("utf-8") == expected


def test_the_long_conversation_splits_into_two_golden_parts(
    export_dir: Path, attachments_dir: Path
) -> None:
    """The one fixture large enough to chunk, with the budget forced down."""
    seed = seed_of(export_dir, attachments_dir, LONG, max_chars=4_000)
    directory = GOLDEN / "max-4000" / LONG
    assert [chunk.text.encode("utf-8") for chunk in seed.chunks] == [
        (directory / "part-01.txt").read_bytes(),
        (directory / "part-02.txt").read_bytes(),
    ]


def test_the_files_on_disk_are_the_golden_bytes(
    export_dir: Path, attachments_dir: Path, tmp_path: Path
) -> None:
    """The hash is of the text; the operator pastes the file. They must agree."""
    seed = seed_of(export_dir, attachments_dir, LONG, max_chars=4_000)
    written = seeding.write_seed(seed, tmp_path / "seeds")
    assert [path.name for path in written] == ["part-01.txt", "part-02.txt"]
    for path, chunk in zip(written, seed.chunks, strict=True):
        assert path.read_bytes() == chunk.text.encode("utf-8")
        assert b"\r\n" not in path.read_bytes()


# --------------------------------------------------------------------------- #
# Acceptance: acknowledgements and hashes
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("max_chars", [50_000, 4_000], ids=["default", "4000"])
def test_every_chunk_ends_with_its_acknowledgement_line(
    export_dir: Path, attachments_dir: Path, max_chars: int
) -> None:
    for outcome in seeds_of(export_dir, attachments_dir, max_chars).values():
        if outcome.seed is None:
            continue
        total = len(outcome.seed.chunks)
        for position, chunk in enumerate(outcome.seed.chunks, start=1):
            expected = f"MIGRATION-ACK {outcome.short_id} {position}/{total}"
            assert chunk.ack == expected
            assert chunk.text.endswith(f"{expected}\n")
            assert (chunk.index, chunk.total) == (position, total)


def test_sha256_of_is_sha256_over_utf8_bytes() -> None:
    """The digest is `orval.hashify`'s now, and `08` compares it against what a
    browser composer holds — so pin it to the definition rather than trust it.

    Non-ASCII on purpose: any encoding but UTF-8 would agree on plain text and
    part ways exactly where a real conversation does.
    """
    text = "Grüße, 世界\n---\nMIGRATION-ACK\n"
    assert seeding.sha256_of(text) == hashlib.sha256(text.encode("utf-8")).hexdigest()


def test_every_sha256_is_the_hash_of_its_own_text(
    export_dir: Path, attachments_dir: Path
) -> None:
    seed = seed_of(export_dir, attachments_dir, LONG, max_chars=4_000)
    for chunk in seed.chunks:
        assert chunk.sha256 == seeding.sha256_of(chunk.text)
    # Distinct parts hash differently: a copy-paste of the first would pass a
    # weaker check and send part one twice.
    assert len({chunk.sha256 for chunk in seed.chunks}) == len(seed.chunks)


# --------------------------------------------------------------------------- #
# Acceptance: the budget
# --------------------------------------------------------------------------- #


def test_no_chunk_exceeds_the_budget(export_dir: Path, attachments_dir: Path) -> None:
    for outcome in seeds_of(export_dir, attachments_dir, 4_000).values():
        if outcome.seed is None:
            continue
        assert all(len(chunk.text) <= 4_000 for chunk in outcome.seed.chunks)


def body_count(text: str) -> int:
    """How many message fragments a part carries.

    A part is `opening`, the fragments, then the footer, joined by the separator,
    so there is always one more separator than there are fragments.
    """
    return text.count(f"\n\n{render.SEPARATOR}\n\n") - 1


def test_the_only_over_budget_chunk_holds_one_indivisible_fragment(
    tmp_path: Path,
) -> None:
    """`04` allows exactly one exception, and this is what forces it: a budget so
    small that the envelope alone spends it, leaving a part that is one fragment
    and still too long. Anything with a second fragment in it could have been
    split further and is a bug."""
    # The hard cap is lifted out of the way: this is about the per-part budget,
    # and 300-character parts spend most of themselves on envelopes.
    settings = Settings(
        workspace=tmp_path,
        seed=SeedSettings(max_chars=300, hard_max_chars=1_000_000),
    )
    outcome = seeding.SeedGenerator(settings).seed(one_turn("z" * 2_000))
    assert outcome.seed is not None

    over = [chunk for chunk in outcome.seed.chunks if len(chunk.text) > 300]
    assert over, "the exception is meant to be reachable; this asserts nothing if not"
    for chunk in over:
        assert body_count(chunk.text) == 1
        # A fragment is not a message, so no part claims it as delivered.
        assert chunk.message_uuids == []


# --------------------------------------------------------------------------- #
# Acceptance: the active path only
# --------------------------------------------------------------------------- #


def test_the_branch_conversation_carries_only_its_active_path(
    export_dir: Path, attachments_dir: Path
) -> None:
    seed = seed_of(export_dir, attachments_dir, BRANCH)
    text = seed.chunks[0].text
    assert OFF_PATH_TEXT not in text
    assert "`dataporter` — a porter carries luggage" in text
    assert seed.messages_represented == 4
    assert seed.limitations == ["branches_dropped:1"]


# --------------------------------------------------------------------------- #
# The model
# --------------------------------------------------------------------------- #


def test_message_uuids_name_the_messages_a_part_fully_contains(
    export_dir: Path, attachments_dir: Path
) -> None:
    seed = seed_of(export_dir, attachments_dir, LONG, max_chars=4_000)
    delivered = [uuid for chunk in seed.chunks for uuid in chunk.message_uuids]
    assert len(delivered) == seed.messages_represented == 40
    assert len(set(delivered)) == len(delivered)


def test_the_short_id_is_the_acknowledgement_token(
    export_dir: Path, attachments_dir: Path
) -> None:
    seed = seed_of(export_dir, attachments_dir, SIMPLE)
    assert seed.short_id == render.short_id(SIMPLE) == "aa000001"


def test_generation_is_byte_identical_across_runs(
    export_dir: Path, attachments_dir: Path
) -> None:
    first = seeds_of(export_dir, attachments_dir)
    second = seeds_of(export_dir, attachments_dir)
    assert [outcome.seed for outcome in first.values()] == [
        outcome.seed for outcome in second.values()
    ]


def test_a_seed_is_frozen_and_closed() -> None:
    with pytest.raises(Exception, match="extra_forbidden"):
        seeding.Seed.model_validate(
            {
                "conversation_uuid": "u",
                "short_id": "u",
                "chunks": [],
                "messages_represented": 0,
                "limitations": [],
                "surprise": 1,
            }
        )


# --------------------------------------------------------------------------- #
# What does not get a seed
# --------------------------------------------------------------------------- #


def test_an_empty_conversation_is_skipped_with_the_plan_s_reason(
    export_dir: Path, attachments_dir: Path
) -> None:
    outcome = seeds_of(export_dir, attachments_dir)[EMPTY]
    assert outcome.seed is None
    assert outcome.reason == "empty_conversation"


def test_a_conversation_over_the_hard_cap_is_skipped(
    export_dir: Path, attachments_dir: Path
) -> None:
    """The plan decides; `04` does not have a rule of its own to disagree with."""
    settings = settings_for(attachments_dir)
    settings = settings.model_copy(
        update={"seed": SeedSettings(max_chars=50_000, hard_max_chars=1_000)}
    )
    export = load_export(export_dir)
    outcomes = list(seeding.SeedGenerator(settings).seeds(export.conversations))
    skipped = {item.short_id: item.reason for item in outcomes if item.seed is None}
    assert skipped["bb000002"] == "seed_over_hard_cap"


def test_a_conversation_id_with_a_control_character_is_refused(tmp_path: Path) -> None:
    """It is not a traversal, but it is not a directory name either — and its
    short id would otherwise put a newline in the `skipped` line."""
    outcome = seeding.SeedGenerator(Settings(workspace=tmp_path)).seed(
        one_turn("Hello", uuid="aa00\n001-1111-4111-8111-111111111111")
    )
    assert outcome.seed is None
    assert outcome.reason == seeding.UNSAFE_CONVERSATION_ID


def test_a_conversation_id_that_is_not_a_path_component_is_refused(
    tmp_path: Path,
) -> None:
    """The uuid becomes a directory name, so it is checked before it is joined."""
    conversation = one_turn("Hello", uuid="../../escape")
    outcome = seeding.SeedGenerator(Settings(workspace=tmp_path)).seed(conversation)
    assert outcome.seed is None
    assert outcome.reason == seeding.UNSAFE_CONVERSATION_ID


# --------------------------------------------------------------------------- #
# Writing
# --------------------------------------------------------------------------- #


def test_writing_replaces_the_parts_that_were_there_before(
    export_dir: Path, attachments_dir: Path, tmp_path: Path
) -> None:
    """A seed that shrinks from two parts to one must not leave part-02 behind for
    `11` to list and `12` to paste."""
    root = tmp_path / "seeds"
    seeding.write_seed(seed_of(export_dir, attachments_dir, LONG, 4_000), root)
    assert (root / LONG / "part-02.txt").exists()

    seeding.write_seed(seed_of(export_dir, attachments_dir, LONG), root)
    assert sorted(path.name for path in (root / LONG).iterdir()) == ["part-01.txt"]


def test_writing_refuses_a_uuid_that_is_not_a_path_component(tmp_path: Path) -> None:
    """The generator skips it first; this is the guard for `12`, which calls
    `write_seed` directly."""
    seed = seeding.Seed(
        conversation_uuid="../escape",
        short_id="escape",
        chunks=[],
        messages_represented=0,
        limitations=[],
    )
    with pytest.raises(Exception, match="not a usable directory name"):
        seeding.write_seed(seed, tmp_path)
    assert not (tmp_path.parent / "escape").exists()


# --------------------------------------------------------------------------- #
# The command
# --------------------------------------------------------------------------- #


def run_seeds(
    runner: CliRunner, export_dir: Path, *arguments: str
) -> tuple[int, str, str]:
    result = runner.invoke(
        cli.app, ["seeds", str(export_dir), *arguments], catch_exceptions=False
    )
    return result.exit_code, result.stdout, result.stderr


def test_seeds_writes_the_workspace_and_prints_one_line_per_conversation(
    runner: CliRunner, workspace: Path, export_dir: Path
) -> None:
    code, out, err = run_seeds(runner, export_dir)
    assert code == ExitCode.OK
    assert out == (
        "aa000001  parts=1  chars=639\n"
        "bb000002  parts=1  chars=7303\n"
        "cc000003  parts=1  chars=738\n"
        "dd000004  parts=1  chars=834\n"
        "ee000005  parts=1  chars=819\n"
    )
    # The one conversation with nothing to migrate, and the reason, on stderr.
    assert err == "skipped ff000006: empty_conversation\n"
    written = sorted(
        path.relative_to(workspace / "migration" / "seeds").as_posix()
        for path in (workspace / "migration" / "seeds").rglob("*.txt")
    )
    assert written == [f"{uuid}/part-01.txt" for uuid in sorted(MIGRATABLE)]


def test_seeds_prints_no_titles_and_no_message_text(
    runner: CliRunner, workspace: Path, export_dir: Path
) -> None:
    """§10: nothing on stdout that a screen-share would leak."""
    _, out, err = run_seeds(runner, export_dir)
    for forbidden in ("Listing files", "Postgres", "pathlib", OFF_PATH_TEXT):
        assert forbidden not in out + err


def test_seeds_honours_out_and_only(
    runner: CliRunner, workspace: Path, export_dir: Path, tmp_path: Path
) -> None:
    out_dir = tmp_path / "elsewhere"
    code, out, _ = run_seeds(
        runner, export_dir, "--only", BRANCH, "--out", str(out_dir)
    )
    assert code == ExitCode.OK
    assert out == "ee000005  parts=1  chars=819\n"
    assert [path.name for path in sorted(out_dir.iterdir())] == [BRANCH]
    assert not (workspace / "migration" / "seeds").exists()


def test_seeds_keeps_export_order_whatever_order_only_was_typed(
    runner: CliRunner, workspace: Path, export_dir: Path, tmp_path: Path
) -> None:
    """Two runs of the same command print the same lines; `06` owns selection."""
    code, out, _ = run_seeds(
        runner, export_dir, "--only", BRANCH, "--only", SIMPLE, "--out", str(tmp_path)
    )
    assert code == ExitCode.OK
    assert out.splitlines() == [
        "aa000001  parts=1  chars=639",
        "ee000005  parts=1  chars=819",
    ]


def test_seeds_rejects_an_unknown_conversation(
    runner: CliRunner, workspace: Path, export_dir: Path
) -> None:
    """A typo is an operator mistake, not an empty selection."""
    code, out, err = run_seeds(runner, export_dir, "--only", "nope")
    assert code == ExitCode.USAGE
    assert err == "error: conversation not in export: nope\n"
    assert out == ""


def test_seeds_exits_4_when_nothing_could_be_seeded(
    runner: CliRunner, workspace: Path, export_dir: Path
) -> None:
    code, out, err = run_seeds(runner, export_dir, "--only", EMPTY)
    assert code == ExitCode.NOTHING_TO_DO
    assert out == ""
    assert err == "skipped ff000006: empty_conversation\n"


def test_seeds_writes_the_files_but_no_progress_when_quiet(
    runner: CliRunner, workspace: Path, export_dir: Path
) -> None:
    result = runner.invoke(
        cli.app,
        ["-q", "seeds", str(export_dir), "--only", SIMPLE],
        catch_exceptions=False,
    )
    assert result.exit_code == ExitCode.OK
    assert result.stdout == ""
    assert (workspace / "migration" / "seeds" / SIMPLE / "part-01.txt").exists()


def test_seeds_rejects_a_missing_export(runner: CliRunner, workspace: Path) -> None:
    result = runner.invoke(cli.app, ["seeds", "./nowhere"], catch_exceptions=False)
    assert result.exit_code == ExitCode.USAGE
    assert result.stderr == "error: export not found: ./nowhere\n"
